name: "Master Build, Test & Deploy"

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set node version
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install
      run: |
        npm install

    - name: Production Build
      if: success()
      run: npx grunt prod

    - name: Prepare for GitHub Pages
      if: success()
      run: npx grunt copy:ghPages

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/master'
      uses: crazy-max/ghaction-github-pages@5859b4ea7efe6b470a5b19c570460eae9323aefc # v3
      with:
        target_branch: gh-pages
        build_dir: ./build/prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
